apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd          
spec:
  project: default            
  source:
    repoURL: https://github.com/GHARBIyasmine/gitops-platform-demo.git
    targetRevision: main
    path: apps/guestbook/overlays/dev
  destination:
    server: https://dev.vc-dev:443
    namespace: guestbook
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true   